{
  "hash": "8c7ac83bbf85dc0836f1e5ca3b331844",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Allrecipes Data Final Project\"\nsubtitle: \"INFO 526 - Summer 2025 - Final Project\"\nauthor: \n  - name: \"Olivia Dodge\"\n    affiliations:\n      - name: \"School of Information, University of Arizona\"\ndescription: \"Final Project\"\nformat:\n   html:\n    code-tools: true\n    code-overflow: wrap\n    embed-resources: true\neditor: visual\nexecute:\n  warning: false\n  echo: false\n---\n\n## Abstract\n\nThis project uses two datasets sourced from an online recipe platform: all_recipes, containing 14,426 recipes with nutritional information, preparation and cook times, and user ratings, and cuisines, containing 2,218 recipes categorized by country of origin alongside similar nutritional and popularity metrics. Together, these datasets offer a basis for exploring how recipe characteristics like time investment and nutritional content relate to user reception and vary across global cuisines.\n\n\n::: {.cell}\n\n:::\n\n\n## Question 1: Prep time, cook time, total time vs. ratings\n\n### Introduction\n\nThe all_recipes dataset contains 14,426 recipes scraped from the online recipe website AllRecipes, and the data contains information on preparation and cook times as well as user-generated average ratings. Many people when cooking are interested in both the amount of time the recipe will take, as well as if they think the recipe is good (this can be based off of other people's reviews). This raises the question: do quicker recipes get rated more favorable because they are convenient, or do longer, more involved recipes receive higher ratings because they produce better results? This question investigates how prep time, cook time, and average time are associated with a recipe's average rating.\n\n### Approach\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  time_group               n mean_rating median_rating sd_rating\n  <fct>                <int>       <dbl>         <dbl>     <dbl>\n1 Quick (<30 min)       2431        4.54           4.6     0.411\n2 Moderate (30-60 min)  4915        4.51           4.6     0.420\n3 Long (>60 min)        5758        4.55           4.6     0.396\n```\n\n\n:::\n:::\n\n\nRecipes with missing or invalid (zero or negative) total time and missing average ratings were filtered out before the analysis was completed. A scatterplot of average rating against total time was created to visualize the overall relationship, with a LOESS smoothing curve overlaid on top to highight a non-linear trend across the range of times. Because the prep time and cook time may behave differently than the total time (for example, a recipe with a long cook time, like a casserole, is much different than a recipe with a large amount of prep work), a second plot compared trends for prep time and cook time separately. The recipes were grouped into three categories based on the total time quick (under 30 minutes), moderate (30 to 60 minutes), and long (over 60 minutes), and a boxplot was used to compare the distribution of ratings in these groups. Summary statistics (mean, median, and standard deviation) were also calculated for each time group to supplement the visual. Looking at the summary stats, there is not much difference in the groups. They all have a mean rating of around 4.5, and a median of 4.6.\n\n### Analysis (ggplot 2 required)\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html/q1-scatterplot-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html/q1-loess-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html/q1-boxplot-1.png){width=672}\n:::\n:::\n\n\n### Discussion\n\nIn all 3 visualizations, the recipe time does not show a meaningful relationship with average rating. The scatterplot's LOESS curve is almost flat, hovering around a rating of 4.5 to 4.6 regardless of the total time. There is a small dip for short recipes and an uptick for the highest time values. The summary statistics also reflect this, as the mean ratings only vary from 4.51 to 4.55 and the median ratings are all 4.6. The boxplot confirms this as well, showing that the distributions are similar between quick, moderate, and long recipes.\n\nThe prep time vs cook time comparison shows some divergence at the extremes. The ratings associated with cook time trend upward through 100 minutes, and then begin to decline. Meanwhile, the ratings associated with prep time peak earlier (around 70 minutes) and then decline more sharply for recipes with longer prep times. This suggests that while moderate cook times may be more preferred, recipes that require a long hands-on prep time may lead to lower ratings due to more work being done by the cook. However, since the rating range is very small, so the main takeaway is that recipe time is not a small predictor of a recipe's rating. Users overall appear to rate the recipes well regardless of how much time the recipe requires.\n\n## Question 2\n\n### Introduction\n\nThe cuisines dataset contains 2,218 recipes categorized by country of origin, along with nutritional information including protein, fat, and carbohydrate content per serving. Cuisines around the world are often associated with particular nutritional profiles, shaped by regional ingredients and traditional cooking methods. The question here is do recipes from different countries actually differ in their macronutrient content, and if so, in what ways? This examines how protein, fat, and carb content vary across the three most common cuisine categories represented in the dataset.\n\n### Approach\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  country       n mean_protein mean_fat mean_carbs\n  <chr>     <int>        <dbl>    <dbl>      <dbl>\n1 Brazilian    64         11.1     13.5       36.1\n2 Canadian     66         15.3     18.5       39.7\n3 Filipino     65         19.3     19.2       26.6\n```\n\n\n:::\n:::\n\n\nBecause the dataset includes a large number of countries, the analysis was narrowed to only the three most frequently occuring cuisines: Brazillian, Canadian, and Filipino, each containing 64-66 recipes. Recipes with missing fat, protein, or carb values were removed prior to analysis. To compare the nutrient distributions across cuisines, the nutrient columns were reshaped inot long format and visualized using faceted boxplots, one panel per nutrient, showing the spread and median of each nutrient and allowing them to be compared side by side. Additionally, a grouped bard chart was created showing the mean amount of each nutrient by cuisine, along with summary statistics showing the mean of each group. As shown, the countries all had different averages of the protein, fat, and carbohydrates.\n\n### Analysis (ggplot2 required)\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html/q2-boxplot-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html/q2-bar-chart-means-1.png){width=672}\n:::\n:::\n\n\n### Discussion\n\nThe visualizations reveal small but consistent differences in macronutrient profiles across the three cuisines. FIlipino recipes have the highest average protein content (19.3g), which is considerably more than Brazillian recipes (11.1g). Canadian recipes fall in between at 15.3g. This pattern is visible in both the boxplot and the bar chart. This may reflect the amount of meat, seafood and egg dishes in Filipino foods. Fat content is more similar among the groups, as Canadian and Filipino cuisines average around 18 to 19 grams while Brazilian recipes are lower at 13.5 grams. However, there are high fat outliers in both Canadian and Filipino recipes, suggesting that the fat content varies widely within these cuisines. Carbohydrate content shows the most separation among the nutrients, with the Canadian recipes having the highest carb content, then Brazilian, then Filipino. This could suggest that the portion sizing or specific dishes sampled in this dataset are driving these values. Overall, the data suggests that the cuisine type is associated with some differences in macronutrient composition (especially for protein), but the overlap and outliers across groups indicate that the nutrient content can vary a lot within a singular cuisine just as much as it does between cuisines.\n\n## References\n\nData from here: <https://github.com/rfordatascience/tidytuesday/blob/main/data/2025/2025-09-16/readme.md>\n\nLink to presentation video: <https://youtu.be/wbZoiSe8e9E>\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}