{
  "hash": "9149c9329d8cc98245e422ef8827210e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Allrecipes Data Final Project\"\nsubtitle: \"Proposal\"\nauthor: \n  - name: \"Olivia Dodge\"\n    affiliations:\n      - name: \"School of Information, University of Arizona\"\ndescription: \"Proposal for final project\"\nformat:\n  html:\n    code-tools: true\n    code-overflow: wrap\n    code-line-numbers: true\n    embed-resources: true\neditor: visual\ncode-annotations: hover\nexecute:\n  warning: false\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\n##install.packages(\"tidytuesdayR\")\nlibrary(tidytuesdayR)\nlibrary(tidyverse)\n\ntuesdata <- tidytuesdayR::tt_load('2025-09-16')\n\nall_recipes <- tuesdata$all_recipes\ncuisines <- tuesdata$cuisines\n```\n:::\n\n\n## Dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(all_recipes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 14,426\nColumns: 16\n$ name           <chr> \"Chewy Whole Wheat Peanut Butter Brownies\", \"Pumpkin Pi…\n$ url            <chr> \"https://www.allrecipes.com/recipe/140717/chewy-whole-w…\n$ author         <chr> \"DMOMMY\", \"Bobbie Susan\", \"Bren\", \"Sarah Brekke\", \"Proc…\n$ date_published <date> 2020-06-18, 2022-09-26, 2018-06-08, 2025-03-03, 2024-1…\n$ ingredients    <chr> \"⅓ cup margarine, softened, ⅔ cup white sugar, ½ cup pa…\n$ calories       <dbl> 222, 477, 354, 356, 366, 709, 466, 782, 355, 395, 378, …\n$ fat            <dbl> 13, 31, 18, 9, 22, 47, 27, 61, 15, 12, 14, 7, 8, 20, 5,…\n$ carbs          <dbl> 24, 43, 32, 53, 23, 31, 1, 19, 33, 33, 50, 16, 29, 17, …\n$ protein        <dbl> 6, 8, 20, 19, 19, 37, 52, 40, 23, 37, 17, 4, 4, 28, 3, …\n$ avg_rating     <dbl> 4.4, 5.0, 4.8, 4.3, 4.7, 4.2, 4.4, 4.6, 4.7, 4.7, 4.7, …\n$ total_ratings  <dbl> 47, 1, 4, 14, 84, 5, 648, 347, 129, 195, 33, 2, 84, 16,…\n$ reviews        <dbl> 36, 1, 4, 13, 67, 3, 468, 259, 102, 153, 23, 1, 71, 15,…\n$ prep_time      <dbl> 20, 10, 10, 20, 30, 45, 15, 10, 30, 20, 5, 5, 15, 15, 3…\n$ cook_time      <dbl> 35, 5, 75, 40, 95, 80, 45, 190, 480, 55, 0, 5, 60, 30, …\n$ total_time     <dbl> 55, 495, 85, 60, 125, 155, 60, 200, 510, 75, 485, 10, 1…\n$ servings       <dbl> 16, 8, 4, 8, 8, 12, 6, 8, 12, 6, 1, 4, 15, 6, 12, 4, 15…\n```\n\n\n:::\n\n```{.r .cell-code}\nglimpse(cuisines)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 2,218\nColumns: 17\n$ name           <chr> \"Saganaki (Flaming Greek Cheese)\", \"Coney Island Knishe…\n$ country        <chr> \"Greek\", \"Jewish\", \"Australian and New Zealander\", \"Chi…\n$ url            <chr> \"https://www.allrecipes.com/recipe/263750/flaming-greek…\n$ author         <chr> \"John Mitzewich\", \"John Mitzewich\", \"CHIPPENDALE\", \"Hei…\n$ date_published <date> 2024-02-07, 2024-11-26, 2022-07-14, 2025-01-31, 2025-0…\n$ ingredients    <chr> \"1 (4 ounce) package kasseri cheese, 1 tablespoon water…\n$ calories       <dbl> 391, 301, 64, 106, 449, 958, 378, 90, 157, 322, 4, NA, …\n$ fat            <dbl> 25, 17, 3, 9, 23, 24, 10, 5, 6, 16, 0, NA, 21, 2, 66, 8…\n$ carbs          <dbl> 15, 31, 9, 7, 58, 144, 59, 10, 25, 39, 1, NA, 16, 63, 7…\n$ protein        <dbl> 16, 7, 1, 1, 7, 46, 14, 1, 2, 7, 0, NA, 28, 6, 54, 17, …\n$ avg_rating     <dbl> 4.8, 4.6, 4.3, 5.0, 3.8, 4.4, 4.3, NA, 4.6, 5.0, 4.7, 4…\n$ total_ratings  <dbl> 25, 10, 126, 1, 13, 40, 3, NA, 65, 2, 182, 2, 19, 16, 9…\n$ reviews        <dbl> 22, 9, 104, 1, 11, 32, 3, NA, 55, 2, 138, 2, 15, 16, 84…\n$ prep_time      <dbl> 10, 30, 20, 10, 30, 30, 30, 40, 0, 5, 5, 5, 10, 10, 20,…\n$ cook_time      <dbl> 5, 75, 15, 0, 15, 165, 75, 30, 0, 5, 0, 25, 10, 50, 16,…\n$ total_time     <dbl> 15, 180, 180, 10, 45, 675, 585, 155, 0, 10, 5, 30, 50, …\n$ servings       <dbl> 2, 16, 12, 6, 15, 6, 6, 84, 24, 1, 21, 8, 4, 10, 4, 8, …\n```\n\n\n:::\n:::\n\n\nA brief description of your dataset including its provenance, dimensions, etc. as well as the reason why you chose this dataset.\n\nMake sure to load the data and use inline code for some of this information.\n\nThe project uses two datasets: all_recipes and cuisines. The all_recipes dataset has 14,426 rows and 16 columns, representing 14,426 recipes. The columns are name, url, author, date_published, ingredients, calories, fat, carbs, protein, avg_rating, total_ratings, reviews, prep_time, cook_time, total_time, and servings. The cuisines dataset has 2,218 rows and 17 columns represting 2,218 recipes categorized by the country they originated from. . The columns are name, country, url, author, date published, ingredients, calories, fat, carbs, protein, avg_rating, total_ratings, reviews, prep_time, cook_time, total_time, and servings. I chose these datasets because they contain a large amount of recipes and have information on both recipe popularity and nutritional content. This opens up the project to more types of analysis and potential visualizations!\n\n## Questions\n\nThe two questions you want to answer.\n\nQuestion 1: How do the prep time, cook time, and total recipe time affect recipe ratings?\n\nQuestion 2: How do protein, fat, and carb content vary across different cuisine categories?\n\n## Analysis plan\n\n- A plan for answering each of the questions including the variables involved, variables to be created (if any), external data to be merged in (if any).\n\nFor question 1, I will look at prep time and cook time seperately, as well as the total time to make the recipe. I will make a scatterplot of the rating versus total time. Additionally, I will split the times into groups based on total time (ie. quick recipes under 30 minutes, moderate recipes 30-60 minutes, and long recipes that are over an hour) and make a boxplot of the ratings across the time groups. This will identify whether recipes that require longer or shorter amounts of time receive different ratings from users.\n\nx = Time variable (prep_time, cook_time, or total_time)\n\ny = avg_rating\n\nFor question 2, I will make boxplots comparing the nutrient distributions across different cuisines to see how the nutrients differ in different types of food. I will use country as the cuisine category. Because the dataset contains many countries, the analysis will focus on the 3 most common cuisine types. Additionally, I will also look at more basic summary statistics like the average amount of nutrients in cuisine types.\n\nVariables are country, protein, fat, and carbs.\n\n| Task Name | Status | Due | Priority | Summary |\n|----|----|----|----|----|\n| Proposal | Complete | June 17 | Medium | Submitted final proposal |\n| Peer Review | Complete | June 13 | Low | Completed 1 peer review; other had 404 repository errors |\n| Write-Up | Incomplete | July 3 | Medium |  |\n| Presentation+Slides | Incomplete | July 3 | Medium |  |\n| Question 1 Visuals | Incomplete | June 26 | High | Start these visuals first! |\n| Question 2 Visuals | Incomplete | June 28 | High | Finish with these visuals |\n",
    "supporting": [
      "proposal_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}